### ISSUE TITLE
Edit availability for tutors (backend)

### ISSUE THREAD

**Issue by AlexisDougherty13** [WillBAnders/TutorsVILLE#119]

**Comment by AlexisDougherty13** [comment]
From Cole on Discord:  "availability is a tuple of data with the parameters of [day, startTime, endTime]"

**Comment by WillBAnders** [comment]
Frontend: #111

**Comment by AlexisDougherty13** [comment]
Turning it into json, current idea is (similar to "tutoring" in profile edit):
{
{"day": "Monday", "startTime": "0800", "endTime": "1200", "action": true},
{"day": "Monday", "startTime": "1400", "endTime": "1500", "action": true},
{"day": "Tuesday", "startTime": "1000", "endTime": "1700", "action": false},
}

where action = true means add and action = false means remove

**Comment by AlexisDougherty13** [comment]
Latest json model:
```
{
    "availability": 
    [
        {"day": "Monday", "startTime": "0800", "endTime": "1200", "action": true},
        {"day": "Monday", "startTime": "1400", "endTime": "1500", "action": true},
        {"day": "Tuesday", "startTime": "1000", "endTime": "1700", "action": true}
    ]
}

```

**Comment by AlexisDougherty13** [comment]
Corrected, typo in last one:
```
{
    "availability": 
    [
        {"day": "Monday", "startTime": "8:00 AM", "endTime": "12:00 PM", "action": true},
        {"day": "Tuesday", "startTime": "8:00 AM", "endTime": "12:00 PM", "action": false},
        {"day": "Tuesday", "startTime": "10:40 AM", "endTime": "5:00 PM", "action": true}
    ]
}
```
