### ISSUE TITLE
Email verification when creating account

### ISSUE THREAD

**Issue by AlexisDougherty13** [WillBAnders/TutorsVILLE#23]
Make sure it is a valid email when account is created

**Comment by AlexisDougherty13** [comment]
When creating a new account, validate the email used before creating the account.

**Comment by WillBAnders** [comment]
Validate needs a precise definition. We should check for obviously incorrect emails (e.g. missing `@`), but beyond that this basically requires sending a confirmation email to the address. Not opposed to trying to do that but definitely a stretch goal.
