### ISSUE TITLE
Users need a default tutor entry

### ISSUE THREAD

**Issue by AlexisDougherty13** [WillBAnders/TutorsVILLE#79]
Sign up is the same for users and tutors, so all users have the opportunity to be a tutor.

All users are tutors, just not all users have filled it out.
Maybe combine the user and tutor table together or just add the user's entry to the tutor page with default values.

**Comment by WillBAnders** [comment]
Combining the tables would result in storing additional data only used for tutors for each user, and tutors are a small proportion of all users. There may also be reasons to require approval for a tutor account, such as having been a TA at the university, completed a background check, or whatever else. It's better that they're kept separate and users have to request the creation of a tutor account.
